# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espID', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PWM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('pretty_name', models.CharField(default='', max_length=200)),
                ('setting', models.IntegerField(default=0)),
                ('on', models.BooleanField(default=False)),
                ('channel', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esp.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('pretty_name', models.CharField(default='', max_length=200)),
                ('on', models.BooleanField(default=False)),
                ('channel', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esp.Device')),
                ('pwm', models.ManyToManyField(to='esp.PWM')),
            ],
        ),
    ]
