# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwm',
            name='switch',
        ),
        migrations.AddField(
            model_name='switch',
            name='pwm',
            field=models.ManyToManyField(to='esp.PWM'),
        ),
    ]
