# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0002_auto_20160513_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwm',
            name='pretty_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='switch',
            name='pretty_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
