# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0002_auto_20160519_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwm',
            name='name',
            field=models.CharField(default='light', max_length=20),
        ),
    ]
