# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0003_auto_20160514_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwm',
            name='channel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='switch',
            name='channel',
            field=models.IntegerField(default=0),
        ),
    ]
