# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0004_auto_20161113_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwm',
            name='nodim',
            field=models.BooleanField(default=False),
        ),
    ]
