# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0006_auto_20161114_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwm',
            name='fpwidth',
            field=models.IntegerField(default=30, verbose_name='Fire Pulse Width'),
        ),
    ]
